name: build-and-deploy
permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make libncurses5-dev perl podhtml mingw-w64
      
      - name: Build BusyBox-W32
        run: |
          make mingw64_defconfig
          make -j$(nproc)
          mkdir -p build
          mv ./busybox.exe build/busybox64.exe
          make mingw32_defconfig
          make -j$(nproc)
          mv ./busybox.exe build/busybox32.exe
      
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build/busybox64.exe
            build/busybox32.exe
